### PR TITLE
Self reconcile

### LINKED ISSUE #57: Self-Reconcilation
The firewall crd should contain a firewall-controller version that is managed by gardener-extension-provider-metal.

The firewall-controller checks for changes and replaces itself, exits and gets restarted by systemd in the new version.

With that, we could also use the release-drafter approach and hold the firewall-controller version in the release vector.

### PR DESCRIPTION
**Pull request by mwindower**
- self-reconcile firewall-controller binary based on the version given in the firewall spec - closes #57 
- proper use of release-drafter
- release firewall-controller also as binary together with SHA256 checksum
- controller-gen@v0.4.0

needs adoption in gepm, cloud-api and cloudctl

### CODE REVIEW

**Comment by majst01** [comment]
Two questions comes in mind:
- can the binary be replaced "in-place", during my work in the https://github.com/metal-stack/updater i found that metalctl for example cant be overwritten during it is running.
- What if the new binary is able to run, but wont be able to connect to the k8s cluster for example, then we end up with a dead firewall-controller, and this will happen through the whole fleet once the version is updated. I dont have a good answer to this except that we introduce a second daemon which checks if firewall-controller is running smoothly after a upgrade and if not replace it with the last good known version.

**Comment by mwindower** [comment]
- I wrote a small test program to show that "in-place" update works: https://gist.github.com/mwindower/c0d28eda63f4a2310696680d98855fe0
- your second concern was about a setup with a new firewall-controller that could possibly not communicate with older k8s api server versions?

**Comment by majst01** [comment]
No second concern is howto handle a situation if the update fails for whatever reason, how do we come back to the previous known stable state.

**Comment by mwindower** [comment]
For normal errors like download / checksum errors, the controller does a retry already.

If `os.Rename` fails from the temp location of the new binary to the real location fails, we should have a backup of the old version? - this is not yet covered.

**Comment by majst01** [comment]
Or if we specify a broken version, all firewalls will be borked, this is my concern

**Comment by mwindower** [comment]
What means borked? We would definitely update firewall-controller versions in a controlled manner... meaning setting it with `cloudctl cluster update`

**Comment by majst01** [comment]
OK, lets go for it, agreed

**Review by majst01 — APPROVED** [review]

**Pull request merged**
