### PR TITLE
Fix for traffic accounting

### PR DESCRIPTION
**Pull request by majst01**
fix for #95

### CODE REVIEW

**Comment by majst01** [comment]
@Gerrit91 we should try this with our integration

**Review by mwindower — APPROVED** [review]
lgtm but needs to be checked on a physical test cluster.

**Comment by majst01** [comment]
Still counters are reset ever few seconds:

```
root@shoot--pskqmw--stefan2-firewall-44522:~# nft list counters
table ip firewall {
        counter internal_in {
                packets 326 bytes 230214
        }
        counter internal_out {
                packets 327 bytes 46666
        }
        counter external_in {
                packets 3 bytes 343
        }
        counter external_out {
                packets 2 bytes 194
        }
        counter drop_total {
                packets 1 bytes 40
        }
        counter drop_ratelimit {
                packets 0 bytes 0
        }
}
root@shoot--pskqmw--stefan2-firewall-44522:~# nft list counters
table ip firewall {
        counter internal_in {
                packets 8 bytes 14041
        }
        counter internal_out {
                packets 10 bytes 769
        }
        counter external_in {
                packets 0 bytes 0
        }
        counter external_out {
                packets 0 bytes 0
        }
        counter drop_total {
                packets 0 bytes 0
        }
        counter drop_ratelimit {
                packets 0 bytes 0
        }
}


```

I think this is because the nft rules are reloaded to often

**Comment by GrigoriyMikhalkin** [comment]
@majst01 Updated PR. Added CWNP checksum comparison, before reconciling nftables.

**Comment by majst01** [comment]
@GrigoriyMikhalkin works ! Thanks ! can you update your other two branches and that i can test these as well

**Pull request merged**
